apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
  labels:
    app: netperf-server
    role: local
spec:
  containers:
    - image: registry.baidubce.com/csm/netperf-latest:latest
      command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]
      imagePullPolicy: Always
      name: netperf
      ports:
        - name: netperf-port
          containerPort: 4444
        - name: iperf-port
          containerPort: 5210
  restartPolicy: Always
#  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: role
#                operator: In
#                values:
#                  - local
#          topologyKey: kubernetes.io/hostname
#    podAntiAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: role
#                operator: In
#                values:
#                  - remote
#          topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: netperf-headless-svc
  labels:
    app: netperf-headless-svc
spec:
  ports:
    - name: netperf-port
      port: 4444
      targetPort: 4444
    - name: iperf-port
      port: 5201
      targetPort: 5201
  clusterIP: None
  selector:
    app: netperf-server
---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client
  labels:
    app: netperf-client
    role: local
spec:
  containers:
    - image: registry.baidubce.com/csm/netperf-latest:latest
      command:
        - sleep
        - "7200"
      imagePullPolicy: Always
      name: netperf
  restartPolicy: Always
#  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: role
#                operator: In
#                values:
#                  - local
#          topologyKey: kubernetes.io/hostname
#    podAntiAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: role
#                operator: In
#                values:
#                  - remote
#          topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netperf-deploy
  labels:
    app: netperf-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: remote
  template:
    metadata:
      labels:
        app: netperf-remote
        role: remote
    spec:
      containers:
        - name: netperf-remote
          image: registry.baidubce.com/csm/netperf-latest:latest
          imagePullPolicy: Always
          command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]
          ports:
            - name: netperf-port
              containerPort: 4444
            - name: iperf-port
              containerPort: 5210
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: role
#                    operator: In
#                    values:
#                      - local
#              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: netperf-remote-svc
spec:
  selector:
    role: remote
  type: ClusterIP
  ports:
    - name: netperf-port
      port: 4444
      targetPort: 4444
    - name: iperf-port
      port: 5201
      targetPort: 5201